"""Status and mode constants for pipeline entities."""

SOURCE_STATUS_NEW = "new"
SOURCE_STATUS_ANALYZING = "analyzing"
SOURCE_STATUS_DONE = "done"
SOURCE_STATUS_SEGMENTED = "segmented"
SOURCE_STATUS_FAILED = "failed"
SOURCE_STATUS_SKIPPED = "skipped"

SOURCE_TYPE_FILE = "file"
SOURCE_TYPE_URL = "url"

CLIP_STATUS_CUT = "cut"
CLIP_STATUS_FORMATTING = "formatting"
CLIP_STATUS_READY = "ready"
CLIP_STATUS_FAILED = "failed"
CLIP_STATUS_REVIEW = "review"
CLIP_STATUS_APPROVED = "approved"
CLIP_STATUS_REJECTED = "rejected"
CLIP_STATUS_PUBLISHED = "published"

ACCOUNT_STATUS_ACTIVE = "active"
ACCOUNT_STATUS_PAUSED = "paused"
ACCOUNT_STATUS_BLOCKED = "blocked"

POST_STATUS_SCHEDULED = "scheduled"
POST_STATUS_PUBLISHED = "published"
POST_STATUS_FAILED = "failed"

REVIEW_MODE_MANUAL = "manual"
REVIEW_MODE_AUTO = "auto"

EVENT_SOURCE_CREATED = "created"
EVENT_SOURCE_DUPLICATE_SKIPPED = "duplicate_skipped"
EVENT_SOURCE_ANALYZED = "analyzed"
EVENT_SOURCE_ANALYZE_FAILED = "analyze_failed"
EVENT_SOURCE_SKIPPED_TOO_SHORT = "skipped_too_short"
EVENT_SOURCE_RETRIED = "retried"
EVENT_SOURCE_SEGMENTED = "segmented"
EVENT_SOURCE_SEGMENT_FAILED = "segment_failed"
EVENT_CLIP_CREATED = "clip_created"
EVENT_CLIP_FORMATTED = "clip_formatted"
EVENT_CLIP_FORMAT_FAILED = "clip_format_failed"
EVENT_CLIP_REVIEW_PREPARED = "clip_review_prepared"
EVENT_CLIP_APPROVED = "clip_approved"
EVENT_CLIP_REJECTED = "clip_rejected"
EVENT_SOURCE_RESET = "source_reset"
